/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ucloud_ulive_example_ext_agora_RemoteDataObserver */

#ifndef _Included_com_ucloud_ulive_example_ext_agora_RemoteDataObserver
#define _Included_com_ucloud_ulive_example_ext_agora_RemoteDataObserver
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ucloud_ulive_example_ext_agora_RemoteDataObserver_UNINIT
#define com_ucloud_ulive_example_ext_agora_RemoteDataObserver_UNINIT -1L
/*
 * Class:     com_ucloud_ulive_example_ext_agora_RemoteDataObserver
 * Method:    createObserver
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ucloud_ulive_example_ext_agora_RemoteDataObserver_createObserver
  (JNIEnv *, jobject);

/*
 * Class:     com_ucloud_ulive_example_ext_agora_RemoteDataObserver
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ucloud_ulive_example_ext_agora_RemoteDataObserver_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ucloud_ulive_example_ext_agora_RemoteDataObserver
 * Method:    enableObserver
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_ucloud_ulive_example_ext_agora_RemoteDataObserver_enableObserver
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_ucloud_ulive_example_ext_agora_RemoteDataObserver
 * Method:    enableObserver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_ucloud_ulive_example_ext_agora_RemoteDataObserver_resetRemoteUid(JNIEnv *env, jobject instance,
                                                                jlong wrapperInstance);

#ifdef __cplusplus
}
#endif
#endif
